<footer class="footer py-4 text-center">
  <div class="container">
    <p class="mb-1">&copy; 2025 Point Final - Thierno Alimou Diallo</p>
    <p class="mb-0">Design inspiré par <a href="https://www.creative-tim.com/product/material-dashboard" target="_blank">Material Dashboard</a> de Creative Tim</p>
  </div>
</footer>

<!-- Scripts JS du Template -->
<script src="/assets/js/core/popper.min.js"></script>
<script src="/assets/js/core/bootstrap.min.js"></script>
<script src="/assets/js/material-dashboard.min.js"></script>