<footer class="footer py-4 text-center">
  <div class="container">
    <p class="mb-1">&copy; 2025 Point Final - Thierno Alimou Diallo</p>
    <p class="mb-0">Design inspiré par <a href="https://www.creative-tim.com/product/material-dashboard" target="_blank">Material Dashboard</a> de Creative Tim</p>
  </div>
</footer>

<!-- Scripts JS du Template -->
<script src="/assets/js/core/popper.min.js"></script>
<script src="/assets/js/core/bootstrap.min.js"></script>
<script src="/assets/js/material-dashboard.min.js"></script>

<!-- Bootstrap Bundle (JS) -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-qQ2h3RRoPzU+UAMMbO1bW5nW+9UOp2rOGK+5L/9mIYQ+4FxsylyGxqyk/p3ZG2Qf" crossorigin="anonymous"></script>
